### PR TITLE
Convert acts_as_category to a Rails gem

### PR DESCRIPTION
**Pull request by mbrookes**

### CODE REVIEW

**Comment by halo** [comment]
Hi Matt, I invited you to a team which has write access to this repository. Unless you really don't want to, I suggest you simply accept that invitation and merge the pull request yourself :) Nice work!

**Comment by fsmanuel** [comment]
:+1:

**Comment by mbrookes** [comment]
Okay, done. :smile: If you want the Travis CI badge to update, you'll need to link it to your account (click on the Travis button in the README...)

**Comment by fsmanuel** [comment]
I linked the account.

**Pull request merged**
